Changed to official docker image for elasticsearch

diff --git a/elasticsearch/Dockerfile b/elasticsearch/Dockerfile
--- a/elasticsearch/Dockerfile
+++ b/elasticsearch/Dockerfile
@@ -1,31 +1,60 @@
-FROM openjdk:8u111-jre-alpine
-MAINTAINER Dimitrios Traskas <dtraskas@caci.co.uk>
+FROM openjdk:8-jre
 
-RUN apk -U add bash
+# grab gosu for easy step-down from root
+ENV GOSU_VERSION 1.7
+RUN set -x \
+	&& wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
+	&& wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
+	&& export GNUPGHOME="$(mktemp -d)" \
+	&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
+	&& gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
+	&& rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc \
+	&& chmod +x /usr/local/bin/gosu \
+	&& gosu nobody true
 
-ENV ES_VERSION=5.1.1
+# https://artifacts.elastic.co/GPG-KEY-elasticsearch
+RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4
 
-ADD https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.tar.gz /tmp/es.tgz
-RUN cd /usr/share && \
-  tar xf /tmp/es.tgz && \
-  rm /tmp/es.tgz
+# https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html
+# https://www.elastic.co/guide/en/elasticsearch/reference/5.0/deb.html
+RUN set -x \
+	&& apt-get update && apt-get install -y --no-install-recommends apt-transport-https && rm -rf /var/lib/apt/lists/* \
+	&& echo 'deb https://artifacts.elastic.co/packages/5.x/apt stable main' > /etc/apt/sources.list.d/elasticsearch.list
+
+ENV ELASTICSEARCH_VERSION 5.1.1
+ENV ELASTICSEARCH_DEB_VERSION 5.1.1
+
+RUN set -x \
+	\
+# don't allow the package to install its sysctl file (causes the install to fail)
+# Failed to write '262144' to '/proc/sys/vm/max_map_count': Read-only file system
+	&& dpkg-divert --rename /usr/lib/sysctl.d/elasticsearch.conf \
+	\
+	&& apt-get update \
+	&& apt-get install -y --no-install-recommends "elasticsearch=$ELASTICSEARCH_DEB_VERSION" \
+	&& rm -rf /var/lib/apt/lists/*
+
+ENV PATH /usr/share/elasticsearch/bin:$PATH
+
+WORKDIR /usr/share/elasticsearch
+
+RUN set -ex \
+	&& for path in \
+		./data \
+		./logs \
+		./config \
+		./config/scripts \
+	; do \
+		mkdir -p "$path"; \
+		chown -R elasticsearch:elasticsearch "$path"; \
+	done
+
+COPY config ./config
+
+VOLUME /usr/share/elasticsearch/data
+
+COPY docker-entrypoint.sh /
 
 EXPOSE 9200 9300
-
-ENV ES_HOME=/usr/share/elasticsearch-$ES_VERSION \
-    DEFAULT_ES_USER=elasticsearch \
-    DISCOVER_TRANSPORT_IP=eth0 \
-    DISCOVER_HTTP_IP=eth0 \
-    ES_JAVA_OPTS="-Xms1g -Xmx1g"
-
-RUN adduser -S -s /bin/sh $DEFAULT_ES_USER
-
-VOLUME ["/data","/conf"]
-
-WORKDIR $ES_HOME
-
-COPY java.policy /usr/lib/jvm/java-1.8-openjdk/jre/lib/security/
-COPY start /start
-COPY log4j2.properties $ES_HOME/config/
-
-CMD ["/start"]
+ENTRYPOINT ["/docker-entrypoint.sh"]
+CMD ["elasticsearch"]
